### ISSUE TITLE
[FEATURE] Saving and optimizing resource previews 

### ISSUE THREAD

**Issue by VeckoTheGecko** [ClimateTown/knowledge-hub#219]
**Describe your suggested improvement**
Currently [`get_og_previews.py`](https://github.com/ClimateTown/knowledge-hub/blob/main/scripts/get_og_previews.py) only saves the URL for the preview (which is hosted on an external site). This means that the performance of our site is tied to the sizes of these external images and the servers they're hosted on.

Saving these images during the scaping process (resizing them to work in the resources page, and potentially using modern web image formats) would help with performace on the website.

**Describe the benefit**
Performance

**Would you be capable/willing to implement the improvement?**
No

**Additional comments**
Comment below if you'd like to work on this.

**Comment by VeckoTheGecko** [comment]
[Possible file naming for preview images](https://stackoverflow.com/a/74052716)

**Comment by JarrodBaniqued** [comment]
Perhaps there should also be a mechanism by which GitHub contributors can submit their own image files for the greyed-out blank previews and they'll be put into the source code.

**Comment by VeckoTheGecko** [comment]
I think that manually specifying thumbnails like this is a bit of a headache to manage (and also may be detached from the site creator and how they want their site to be presented). I think automated tools to determine the thumbnail could be possible (e.g. if the `og:description` tag (what the current implementation uses) isn't there the webpage can be loaded and a screenshot is taken of it). Even then, I'd say its more effort than its worth.

Site owners should make sure they have meta tags if they want sites to use proper previews/

**Comment by Lyrete** [comment]
I could take a look at this when I have time, very interested in contributing, (can probably also do the parallellization while at it) :) Is your idea just to have a data folder of the images after the scraping or where would we store them?

**Comment by VeckoTheGecko** [comment]
Thanks for the interest @Lyrete ! Yes, hosting them in the static folder would be awesome. And indeed, doing #218 while you're at it would be an amazing addition :D . Re #218, I was watching a [Arjan Codes video](https://www.youtube.com/watch?v=OPyoXx0yA0I) a couple days ago comparing the different options for parallelizing web requests. Might be a good starting point (from my understanding, the httpx package looks to be a good option)

**Comment by Lyrete** [comment]
yeah I have some experience using httpx at work for similar things so I think it would work pretty well. I will take a look on the weekend (or during the week if I don't have much to do at work)

**Comment by Lyrete** [comment]
What was the idea with the naming schema? For an initial thing I implemented a 8 char hex digest off the resource name, but I think something should be done to make sure there's no possibility of name collisions (unlikely but still good practice I think). Can discuss in the PR too, #373. Considerations on whether it'll refresh the image properly don't really need to be done as the build process redoes the fetching every time anyway (this would be different if the files were cached somewhere between builds, but this is a separate concern).

Otherwise this is fairly done so it's a question of whether you'd prefer two PRs if I do #218 too. That'll probably be a bit larger overhaul to the whole get preview thing itself, because ideally we'd parallelize the entirety of the scraping including the initial soup call too etc.
