### ISSUE TITLE
Add licensing for these resources and the support code

### ISSUE THREAD

**Issue by wolftune** [ClimateTown/knowledge-hub#396]
This seems late since people have already contributed and thus will need to accept a licensing change (unless there was some legal agreement as part of contributing, which I didn't notice mentioned anywhere)

A Free/Libre/Open appropriate license would be really good. I suggest using Creative Commons Attribution Share-Alike (CC-BY-SA) 4.0 See https://creativecommons.org/licenses/by-sa/4.0/ for all the non-code general text and images and whatnot, and I suggest GNU AGPL for the code. These licenses are the most supportive of sharing and adaptation except with a requirement that the freedoms be passed on if anyone else shares or adapts the resources.

**Comment by VeckoTheGecko** [comment]
Thanks for the suggestion @wolftune ! I agree that it would be good to have a permissive license, but I'm more inclined to go for a more "attribution required" license rather than one that requires attribution _and_ maintaining the same license (which may limit the scope of the data/code if other projects want to adopt this but have different license). Thoughts on the [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) license instead? cc @dmlb .

I would also like to limit the license to code and data. I feel like image assets (logos, etc) should remain with the original contributors (or with the core CT team in the case of the CT logo). We can add a note to the README regarding this.

Since this is a major change to the project, it may take a while. Timeline:
- Decide on a license
- Discuss this with core CT team
- PR with license changes
- [probably 1-2 weeks after] PR merge

**Comment by wolftune** [comment]
I guess you mean attribution-required *only*, because CC-BY-SA has the attribution requirement. I am okay with both CC-BY and CC-BY-SA. Both are permissive, both require attribution. And CC-BY is *compatible* still, which means that anything CC-BY *may* be used within CC-BY-SA projects like StrongTowns or Wikipedia.

I tend to favor CC-BY-SA, but I'll *insist* as urgently as I can that licensing be *compatible* with it, so CC-BY is perfectly acceptable while some discriminatory license like the NC or ND clauses are bad because they block healthy uses and create incompatibilities.

I do agree with the suggestion that **trademark** type items be exempted from this licensing. CT logos and branding and so on should not be free to be used by others. There can still be a written trademark-policy that supports reasonable use and clarifies what is acceptable. Trademarks generally do not make sense to have the type of freedoms that fit code and information and overall writings and such.

**Comment by dmlb** [comment]
@VeckoTheGecko the only thing I would have to add is maybe looping in Ed in regards to the redesign, if there is any impact there if that's something we move forward with
